### ISSUE TITLE
[BUG] If neovim is opened without a file as argument, norme.nvim won't work

### ISSUE THREAD

**Issue by vinicius507** [vinicius507/norme.nvim#1]
### Description

If Neovim is opened solely with `nvim`, the norme linter won't run.

### Steps to reproduce

1. `nvim`
2. Open a .c or .h file inside `nvim`
3. Induce a norme error

### Expected Behaviour

Show the error with LSP diagnostics.

### Neovim version

```bash
$ nvim -v
NVIM v0.5.0-dev+1291-gb227cedf8
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az207-747

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by vinicius507** [comment]
I'm gonna test if this is something due to `nvim-lint` or a `norme.nvim` specific error.
@paulo-santana

**Comment by paulo-santana** [comment]
It seems to be something wrong with `norme.nvim`. I tested nvim-lint with pylint and it works fine.

**Comment by eduardomosko** [comment]
Can confirm: Pylint works, so does Flake8, but norme does not

**Comment by eduardomosko** [comment]
Looking in the code, both flake8 and pylint set `stdin=false`. We should check the behavior of another linter that reads from stdin, like shellchek

**Comment by eduardomosko** [comment]
Shellcheck also works

**Comment by paulo-santana** [comment]
When removing the line `ignore_exitcode = true,` from
https://github.com/vinicius507/norme.nvim/blob/1e157c19197fca3e97adfb6cbccf202b43f08ee7/lua/norme.lua#L43-L50

Neovim shows the message `Linter exited with code 1` when reproducing the steps for the problem.

Do we have access to any kind of log from nvim-lint? It's possible that norminette is running correctly, but the plugin isn't capturing the output.

Well, I changed norminette's code to exit with 87 as status code when on error. In the console it works as expected, but Neovim keeps saying that the Linter is exiting with code 1. And it actually exits with 1 even if there's no Norm error in the file. So, yeah, norminette isn't running at all.
