### ISSUE TITLE
Unify generators for .c and .h files

### ISSUE THREAD

**Issue by lagachea** [vinicius507/norme.nvim#22]
Hello,

I created my own null-ls diagnostic source for norminette, and then I found this repo which has a better capture for the pattern matching of error messages. So I switch to use this plugin, and looking at the code and this [PR](https://github.com/vinicius507/norme.nvim/pull/21). I wonder if the goal besides being working with stdin option, is to unify the diagnostic generators.
In my personal generator, i made it works with both .c and .h file and I was using args like so (1)
```lua
args = { "$FILENAME"},
```
instead of (2)
```lua
args = { '--filename', '$FILENAME', '--hfile', '$TEXT' },
args = { '--filename', '$FILENAME', '--cfile', '$TEXT' },

```
which are unified as (3) in the PR
```lua
args = { '--stdin', '--filename', '$FILENAME' }
```
What is the difference for norminette when using (2) instead of (1). I think I am missing something with the options used in (2).

**Comment by vinicius507** [comment]
Greetings, @lagachea!

The purpose was, indeed, to unify the sources. Although `--stdin` flag was not merged into `norminette`. Hence that PR is invalid.

I will close it now. Thanks :)
