### ISSUE TITLE
[BUG] Script stdin-parser is being called twice when adding new lines

### ISSUE THREAD

**Issue by paulo-santana** [vinicius507/norme.nvim#4]
### Description
Whenever you add a new line in a C file by pressing `o` or `i<cr>` inside a indented block (i.e. inside a function or a condition clause), this line will follow the indentation of that block. But, if you hit `<esc>` leaving a blank line, Neovim will erase this line's indentations, leaving you with an empty blank line.

This will cause both `InsertLeave` and `TextChanged` events to trigger the linter at almost the same time.

For some reason, this causes the unexpected behavior of the linter exiting with status code 1 on many of the second calls, and the diagnostics won't show up until another event triggers the linting again.

### Steps to reproduce
1. Open a C source file
2. Have some Norm errors
3. Enter insert mode inside a function and add a new indented blank line (with either `cc`, `i<enter>`, `o`)
4. Hit `<esc>` without changing this line

### Expected behavior
At the very least, the both calls to the linter are supposed to run fine. We should investigate why one of them crashes sometimes. It's possible that my hardware isn't good enough to run these tasks reliably

### Screenshots

In this vídeo I have modified the `stdin-parser` script to write `1\n` in a file i'm monitoring and counting it's lines.
When I press `<esc>` in a blank line, the number of lines in that file increases by 2, indicating that stdin-parser is being called twice. Sometimes this causes the linter to crash so the diagnostics are removed from the buffer.

I also removed `ignore_exitcode = true,`, so Neovim prints `Linter exited with code 1`

https://user-images.githubusercontent.com/7424845/118385563-420a2a00-b5e6-11eb-89ad-c0e8df2d3c30.mp4

[video in youtube](https://youtu.be/BYRdlcJZKEw)

### Additional information

OS: Arch Linux
`norminette` version: `norminette 3.2.95`.
Neovim Version: `v0.5.0-dev+1282-gfbe18d9ca`

```bash
$ uname -r
5.10.36-1-lts

$ nvim -v
NVIM v0.5.0-dev+1282-gfbe18d9ca
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az36-84

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

Hardware specs:
CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
Video: integrated (HD Graphics 520)
Mem: DDR4 2133 MHz
HD: SATA 1TB 5400rpm

**Comment by vinicius507** [comment]
Can you update video file? It is corrupted
